name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
permissions:
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000

    steps:
    - name: Free up disk space
      run: |
        set -x
        # Delete unnecessary files to free up space
        df -h
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session on manually-triggered workflows
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}    
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate local metadata for CI image
      id: meta_ci
      uses: docker/metadata-action@v3
      with:
        images: |
          localhost:5000/okmo/build

    - name: Generate local metadata for Developer image
      id: meta_developer
      uses: docker/metadata-action@v3
      with:
        images: |
          localhost:5000/okmo/develop

    - name: Generate push metadata for CI image
      if: ${{ github.event_name != 'pull_request' }}
      id: meta_ci_push
      uses: docker/metadata-action@v3
      with:
        images: |
          docker.io/okmo/build

    - name: Generate push metadata for Developer image
      if: ${{ github.event_name != 'pull_request' }}
      id: meta_developer_push
      uses: docker/metadata-action@v3
      with:
        images: |
          docker.io/okmo/develop

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build CI docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.build
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta_ci.outputs.tags }}
        labels: ${{ steps.meta_ci.outputs.labels }}
    
    # Enable tmate debugging if previous step fails
    - name: Setup tmate session if Build CI docker image step fails
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

    - name: Build Developer docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.develop
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta_developer.outputs.tags }}
        labels: ${{ steps.meta_developer.outputs.labels }}
        build-args: |
          BASE_IMAGE=localhost:5000/okmo/build:${{ steps.meta_ci.outputs.version }}

    # Enable tmate debugging if previous step fails
    - name: Setup tmate session if Build Developer docker image step fails
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push CI docker image
      if: ${{ github.event_name != 'pull_request' }}
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: localhost:5000/okmo/build:${{ steps.meta_ci.outputs.version }}
        dst: ${{ steps.meta_ci_push.outputs.tags }}

    - name: Push Developer docker image
      if: ${{ github.event_name != 'pull_request' }}
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: localhost:5000/okmo/develop:${{ steps.meta_developer.outputs.version }}
        dst: ${{ steps.meta_developer_push.outputs.tags }}
